# Etapa 1: Construcción
FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
# Compilamos el binario de forma estática
RUN CGO_ENABLED=0 GOOS=linux go build -o main ./cmd/api/main.go

# Etapa 2: Imagen final ultra ligera
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
# Copiamos archivos necesarios si los hay (ej. plantillas, si llegaras a tener)
# COPY --from=builder /app/.env . 

EXPOSE 8080
CMD ["./main"]